// Generated by https://quicktype.io

// export interface PostDatos {
//     acf:               any[];
//     author:            number;
//     author_name:       string;
//     categories:        number[];
//     comment_status:    string;
//     content:           Content;
//     date:              string;
//     date_gmt:          string;
//     especiales:        any[];
//     excerpt:           Content;
//     featured_media:    number;
//     format:            string;
//     guid:              GUID;
//     id:                number;
//     link:              string;
//     meta:              any[];
//     modified:          string;
//     modified_gmt:      string;
//     ping_status:       string;
//     pltv:              any[];
//     publicacion:       any[];
//     publicidades:      any[];
//     "ruta-geografica": number[];
//     slug:              string;
//     status:            string;
//     sticky:            boolean;
//     tags:              number[];
//     tema:              any[];
//     "tema-escaner":    any[];
//     template:          string;
//     title:             GUID;
//     type:              string;
// }

// export interface Content {
//     protected: boolean;
//     rendered:  string;
// }
// Generated by https://quicktype.io

export interface PostCategory {
    id:                     number;
    title:                  string;
    excerpt:                string;
    date:                   string;
    content:                string;
    slug:                   string;
    guid:                   string;
    author:                 string;
    category:               Category[];
    tema:                   any[];
    tema_escaner:           boolean;
    ruta_geografica:        PostTag[];
    featured_image:         FeaturedImage;
    post_tags:              PostTag[];
    autores_escaner:        boolean;
    Youtube_URL:            string;
    mostrar_firma:          boolean;
    colaboradores_escaners: null;
}

export interface Category {
    term_id:              number;
    name:                 string;
    slug:                 string;
    term_group:           number;
    term_taxonomy_id:     number;
    taxonomy:             string;
    description:          string;
    parent:               number;
    count:                number;
    filter:               string;
    cat_ID:               number;
    category_count:       number;
    category_description: string;
    cat_name:             string;
    category_nicename:    string;
    category_parent:      number;
}

export interface FeaturedImage {
    thumbnail: string;
    medium:    string;
    large:     string;
}

export interface PostTag {
    term_id:          number;
    name:             string;
    slug:             string;
    term_group:       number;
    term_taxonomy_id: number;
    taxonomy:         string;
    description:      string;
    parent:           number;
    count:            number;
    filter:           string;
}

// export interface GUID {
//     rendered: string;
// }


// Generated by https://quicktype.io

// export interface PostNotas {
//     id:                     number;
//     title:                  string;
//     excerpt:                string;
//     date:                   string;
//     content:                string;
//     slug:                   string;
//     guid:                   string;
//     author:                 string;
//     category:               Category[];
//     tema:                   any[];
//     tema_escaner:           boolean;
//     ruta_geografica:        PostTag[];
//     featured_image:         FeaturedImage;
//     post_tags:              PostTag[];
//     autores_escaner:        null;
//     Youtube_URL:            null;
//     mostrar_firma:          boolean;
//     colaboradores_escaners: null;
// }

// export interface Category {
//     term_id:              number;
//     name:                 string;
//     slug:                 string;
//     term_group:           number;
//     term_taxonomy_id:     number;
//     taxonomy:             string;
//     description:          string;
//     parent:               number;
//     count:                number;
//     filter:               string;
//     cat_ID:               number;
//     category_count:       number;
//     category_description: string;
//     cat_name:             string;
//     category_nicename:    string;
//     category_parent:      number;
// }

// export interface FeaturedImage {
//     thumbnail: any[];
//     medium:    any[];
//     large:     any[];
// }

// export interface PostTag {
//     term_id:          number;
//     name:             string;
//     slug:             string;
//     term_group:       number;
//     term_taxonomy_id: number;
//     taxonomy:         string;
//     description:      string;
//     parent:           number;
//     count:            number;
//     filter:           string;
// }
